FROM node:20-alpine

# Install dependencies for Strapi
RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev python3

WORKDIR /opt/app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

RUN yarn build

EXPOSE 1340

CMD ["yarn", "develop"]
